# Problem 1: Multiples of 3 or 5


If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [14]:
lis = list(range(1000))

In [13]:
# importing functools for reduce()
import functools
print(functools.reduce(lambda a, b: a+b if (b%3 == 0) or (b%5 == 0) else a, lis))

Sum is :
233168

### reduce() in Python

The reduce(fun,seq) function is used to apply a particular function passed in its argument to all of the list elements mentioned in the sequence passed along.This function is defined in “functools” module.

Working :  

- At first step, first two elements of sequence are picked and the result is obtained.
- Next step is to apply the same function to the previously attained result and the number just succeeding the second element and the result is again stored.
- This process continues till no more elements are left in the container.

# Problem 2: Even Fibonacci numbers


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [26]:
a = 1
b = 2
next = a+b
sum = b

while next < 4000000:
    if next%2 == 0:
        sum += next
    a = b
    b = next
    next = a+b
sum

4613732

### List Comprehension

newlist = [expression for item in iterable if condition == True]

The return value is a new list, leaving the old list unchanged.
Expression is item from the iterable if condition is true
You can also modify item before if gets append to the new list

In [32]:
# The following will extract the first letter of all words in lis with an e 
lis = ["boule", "sapin", "lumière"]
lis2 = [x[0] for x in lis if 'e' in x]
lis2

['b', 'l']

### Unpacking

Unpacking is the process to extract all contents in its own seperate variable

In [51]:
fruits = ["apple", "mango", "papaya"]

a, b, c = fruits
print(f"a: {a}, b:{b} and c:{c}")

a: apple, b:mango and c:papaya

### The asterisk

Use to explode the content or accept any amount of content

In [54]:
# explode the string to add each letter individually in a set
{*"Mississipi"}

{'M', 'i', 'p', 's'}

In [40]:
fruits = ("apple", "mango", "papaya", "pineapple", "cherry")

(green, *tropic, red) = fruits

print(green)
print(tropic)
print(red)

apple
['mango', 'papaya', 'pineapple']
cherry

### Files

In [64]:
f = open('test.txt')
for line in f:
    print(line)
f.close()

patate

poil

nannannan

In [66]:
f = open('test.txt')
content = f.read()
print(type(content))
print(content)
f.close()

<class 'str'>
patate
poil
nannannan

# Problem 3: Largest prime factor

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [96]:
def isPrime(n):
    for i in range(2, n//2):
        if n%i == 0:
            return False
    return True

n = 600851475143
x = 2
factors = []
while n > 1:
    if n%x == 0:
        factors.append(x)
        n /= x
    else:
        x += 1

print(isPrime(factors[-1]))
factors[-1]

True

6857

# Problem 4: Largest palindrome product
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [131]:
palindrome = []
for j in range(999,100,-1):
    for k in range(999,100,-1):
        mult = j*k
        if str(mult) == str(mult)[::-1]:
            palindrome.append(mult)
max(palindrome)

906609

# Problem 5: Smallest multiple

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [152]:
x = 20
found = False
while found != True:
    for i in range(2,21):
#        print(x, i)
        if x%i != 0:
            x += 2
            break
        if i == 20:
            found = True
print(x)

KeyboardInterrupt:

In [148]:
lis = range(2,21)
import functools
print(functools.reduce(lambda a, b: a*b, lis))

2432902008176640000

In [151]:
19*17*13*11*7*5*3

4849845