# Problem 1: Multiples of 3 or 5


If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [14]:
lis = list(range(1000))

In [13]:
# importing functools for reduce()
import functools
print(functools.reduce(lambda a, b: a+b if (b%3 == 0) or (b%5 == 0) else a, lis))

Sum is :
233168

## reduce() in Python

The reduce(fun,seq) function is used to apply a particular function passed in its argument to all of the list elements mentioned in the sequence passed along.This function is defined in “functools” module.

Working :  

- At first step, first two elements of sequence are picked and the result is obtained.
- Next step is to apply the same function to the previously attained result and the number just succeeding the second element and the result is again stored.
- This process continues till no more elements are left in the container.

# Problem 2: Even Fibonacci numbers


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [26]:
a = 1
b = 2
next = a+b
sum = b

while next < 4000000:
    if next%2 == 0:
        sum += next
    a = b
    b = next
    next = a+b
sum

4613732

## List Comprehension

newlist = [expression for item in iterable if condition == True]

The return value is a new list, leaving the old list unchanged.
Expression is item from the iterable if condition is true
You can also modify item before if gets append to the new list

In [32]:
# The following will extract the first letter of all words in lis with an e 
lis = ["boule", "sapin", "lumière"]
lis2 = [x[0] for x in lis if 'e' in x]
lis2

['b', 'l']

## Unpacking

Unpacking is the process to extract all contents in its own seperate variable

In [51]:
fruits = ["apple", "mango", "papaya"]

a, b, c = fruits
print(f"a: {a}, b:{b} and c:{c}")

a: apple, b:mango and c:papaya

## The asterisk

Use to explode the content or accept any amount of content

In [54]:
# explode the string to add each letter individually in a set
{*"Mississipi"}

{'M', 'i', 'p', 's'}

In [40]:
fruits = ("apple", "mango", "papaya", "pineapple", "cherry")

(green, *tropic, red) = fruits

print(green)
print(tropic)
print(red)

apple
['mango', 'papaya', 'pineapple']
cherry

## Files

In [64]:
f = open('test.txt')
for line in f:
    print(line)
f.close()

patate

poil

nannannan

In [66]:
f = open('test.txt')
content = f.read()
print(type(content))
print(content)
f.close()

<class 'str'>
patate
poil
nannannan

# Problem 3: Largest prime factor

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [96]:
def isPrime(n):
    for i in range(2, n//2):
        if n%i == 0:
            return False
    return True

n = 600851475143
x = 2
factors = []
while n > 1:
    if n%x == 0:
        factors.append(x)
        n /= x
    else:
        x += 1

print(isPrime(factors[-1]))
factors[-1]

True

6857

# Problem 4: Largest palindrome product
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [131]:
palindrome = []
for j in range(999,100,-1):
    for k in range(999,100,-1):
        mult = j*k
        if str(mult) == str(mult)[::-1]:
            palindrome.append(mult)
max(palindrome)

906609

# Problem 5: Smallest multiple

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [159]:
x = 20
found = False
while found != True:
    for i in range(2,21):
        if x%i != 0:
            x += 20
            break
        if i == 20:
            found = True
print(x)

232792560

## range

The range function allows you to quickly generate a list of integers, this comes in handy a lot, so take note of how to use it! There are 3 parameters you can pass, a start, a stop, and a step size.

Note that this is a generator function, so to actually get a list out of it, we need to cast it to a list with list(). What is a generator? Its a special type of function that will generate information and not need to save it to memory. We haven't talked about functions or generators yet, so just keep this in your notes for now, we will discuss this in much more detail in later on in your training!

Notice how 11 is not included, up to but not including 11, just like slice notation!

In [164]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Third parameter is step size!

step size just means how big of a jump/leap/step you 

take from the starting number to get to the next number.

In [165]:
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

## enumerate

enumerate is a very useful function to use with for loops. It returns each item and its index

Notice the tuple unpacking!

In [166]:
for i,letter in enumerate('abcde'):

    print("At index {} the letter is {}".format(i,letter))

At index 0 the letter is a
At index 1 the letter is b
At index 2 the letter is c
At index 3 the letter is d
At index 4 the letter is e

## zip

Notice the format enumerate actually returns, let's take a look by transforming it to a list()

list(enumerate('abcde'))

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e')]

It was a list of tuples, meaning we could use tuple unpacking during our for loop. This data structure is actually very common in Python , especially when working with outside libraries. You can use the zip() function to quickly create a list of tuples by "zipping" up together two lists.

In [167]:
mylist1 = [1,2,3,4,5]

mylist2 = ['a','b','c','d','e']

# This one is also a generator! We will explain this later, but for now let's transform it to a list

zip(mylist1,mylist2)

In [169]:
list(zip(mylist1,mylist2))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')]

## in operator

We've already seen the **in** keyword during the for loop, but we can also use it to quickly check if an object is in a list

In [21]:
'x' in ['x','y','z']

True

In [22]:
'x' in [1,2,3]

False

## not in

We can combine **in** with a **not** operator, to check if some object or variable is not present in a list.

In [172]:
'x' not in ['x','y','z']

False

In [173]:
'x' not in [1,2,3]

True

## min and max

Quickly check the minimum or maximum of a list with these functions.

In [174]:
mylist = [10,20,30,40,100]

In [175]:
min(mylist)

10

In [176]:
max(mylist)

100

## random

Python comes with a built in random library. There are a lot of functions included in this random library, so we will only show you two useful functions for now.

In [177]:
from random import shuffle

In [178]:
# This shuffles the list "in-place" meaning it won't return
# anything, instead it will effect the list passed
shuffle(mylist)

In [179]:
mylist

[10, 30, 100, 20, 40]

In [180]:
from random import randint

In [181]:
# Return random integer in range [a, b], including both end points.
randint(0,100)

83

In [182]:
# Return random integer in range [a, b], including both end points.
randint(0,100)

87

## input

In [184]:
input('Enter Something into this box: ')

Enter Something into this box: patate

'patate'

## string usefull functions 

.split(separator, maxsplit) : Splits the string at the specified separator, and returns a list
- separator: Optional. Specifies the separator to use when splitting the string. By default any whitespace is a separator
- maxsplit: Optional. Specifies how many splits to do. Default value is -1, which is "all occurrences"

# Problem 6: Sum square difference


The sum of the squares of the first ten natural numbers is, 385

The square of the sum of the first ten natural numbers is, 3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 2640

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [9]:
import functools
lis = [x**2 for x in range(1, 101)]
su_of_sq = functools.reduce(lambda a, b: a+b, lis)
lis2 = list(range(1, 101))
sq_of_su = functools.reduce(lambda a, b: a+b, lis2)**2
print(su_of_sq - sq_of_su)

-25164150

## map

The map() function executes a specified function for each item in an iterable. The item is sent to the function as a parameter.

map(function, iterables)
- function: Required. The function to execute for each item
- iterable: Required. A sequence, collection or an iterator object. You can send as many iterables as you like, just make sure the function has one parameter for each iterable.

# Problem 54: Poker hands


<p>In the card game poker, a hand consists of five cards and are ranked, from lowest to highest, in the following way:</p>
<ul><li><b>High Card</b>: Highest value card.</li>
<li><b>One Pair</b>: Two cards of the same value.</li>
<li><b>Two Pairs</b>: Two different pairs.</li>
<li><b>Three of a Kind</b>: Three cards of the same value.</li>
<li><b>Straight</b>: All cards are consecutive values.</li>
<li><b>Flush</b>: All cards of the same suit.</li>
<li><b>Full House</b>: Three of a kind and a pair.</li>
<li><b>Four of a Kind</b>: Four cards of the same value.</li>
<li><b>Straight Flush</b>: All cards are consecutive values of same suit.</li>
<li><b>Royal Flush</b>: Ten, Jack, Queen, King, Ace, in same suit.</li>
</ul><p>The cards are valued in the order:<br />2, 3, 4, 5, 6, 7, 8, 9, 10, Jack, Queen, King, Ace.</p>
<p>If two players have the same ranked hands then the rank made up of the highest value wins; for example, a pair of eights beats a pair of fives (see example 1 below). But if two ranks tie, for example, both players have a pair of queens, then highest cards in each hand are compared (see example 4 below); if the highest cards tie then the next highest cards are compared, and so on.</p>
<p>Consider the following five hands dealt to two players:</p>
<div class="center">
<table><tr><td><b>Hand</b></td><td> </td><td><b>Player 1</b></td><td> </td><td><b>Player 2</b></td><td> </td><td><b>Winner</b></td>
</tr><tr><td><b>1</b></td><td> </td><td>5H 5C 6S 7S KD<br /><div class="smaller">Pair of Fives</div></td><td> </td><td>2C 3S 8S 8D TD<br /><div class="smaller">Pair of Eights</div></td><td> </td><td>Player 2</td>
</tr><tr><td><b>2</b></td><td> </td><td>5D 8C 9S JS AC<br /><div class="smaller">Highest card Ace</div></td><td> </td><td>2C 5C 7D 8S QH<br /><div class="smaller">Highest card Queen</div></td><td> </td><td>Player 1</td>
</tr><tr><td><b>3</b></td><td> </td><td>2D 9C AS AH AC<br /><div class="smaller">Three Aces</div></td><td> </td><td>3D 6D 7D TD QD<br /><div class="smaller">Flush  with Diamonds</div></td><td> </td><td>Player 2</td>
</tr><tr><td><b>4</b></td><td> </td><td>4D 6S 9H QH QC<br /><div class="smaller">Pair of Queens<br />Highest card Nine</div></td><td> </td><td>3D 6D 7H QD QS<br /><div class="smaller">Pair of Queens<br />Highest card Seven</div></td><td> </td><td>Player 1</td>
</tr><tr><td><b>5</b></td><td> </td><td>2H 2D 4C 4D 4S<br /><div class="smaller">Full House<br />With Three Fours</div></td><td> </td><td>3C 3D 3S 9S 9D<br /><div class="smaller">Full House<br />with Three Threes</div></td><td> </td><td>Player 1</td>
</tr></table></div>
<p>The file, <a href="project/resources/p054_poker.txt">poker.txt</a>, contains one-thousand random hands dealt to two players. Each line of the file contains ten cards (separated by a single space): the first five are Player 1's cards and the last five are Player 2's cards. You can assume that all hands are valid (no invalid characters or repeated cards), each player's hand is in no specific order, and in each hand there is a clear winner.</p>
<p>How many hands does Player 1 win?</p>

In [70]:
p1 = []
p2 = []

def toNumber(c):
    if c == 'A':
        return 14
    elif c == 'K':
        return 13
    elif c == 'Q':
        return 12
    elif c == 'J':
        return 11
    elif c == 'T':
        return 10
    else:
        return c


for line in open("p054_poker.txt"):
    tmp = line.split()
    #convert type of card to number and create a list of tuples
    p1 = (list(map(lambda a: (toNumber(a[0]), a[1]), tmp[:5])))
    p2 = list(map(lambda a: (toNumber(a[0]), a[1]), tmp[5:]))

    #sort by strength
    p1.sort(reverse=True, key=lambda a: int(a[0]))
    p2.sort(reverse=True, key=lambda a: int(a[0]))
        
    
print(p1, p2)

None [(12, 'D'), ('8', 'C'), ('7', 'C'), ('6', 'C'), ('5', 'C')]